package outbox

import (
	"context"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/vincent-tien/gokit/broker"
)

// mockPublisher records published messages for relay testing.
type mockPublisher struct {
	msgs []broker.Message
	err  error
}

func (m *mockPublisher) Publish(_ context.Context, msgs ...broker.Message) error {
	if m.err != nil {
		return m.err
	}
	m.msgs = append(m.msgs, msgs...)
	return nil
}

func (m *mockPublisher) Close() error { return nil }

func TestEvent_IDAutoGenerated(t *testing.T) {
	e := Event{Topic: "test", Payload: []byte("data")}
	assert.Empty(t, e.ID, "ID should be empty before Store")
}

func TestNewWriter(t *testing.T) {
	w := NewWriter(nil)
	assert.NotNil(t, w)
}

func TestNewRelay_Defaults(t *testing.T) {
	pub := &mockPublisher{}
	r := NewRelay(nil, pub)
	assert.Equal(t, time.Second, r.interval)
	assert.Equal(t, 100, r.batchSize)
}

func TestNewRelay_WithOptions(t *testing.T) {
	pub := &mockPublisher{}
	r := NewRelay(nil, pub,
		WithInterval(5*time.Second),
		WithBatchSize(50),
	)
	assert.Equal(t, 5*time.Second, r.interval)
	assert.Equal(t, 50, r.batchSize)
}

func TestRelay_Start_RespectsContextCancellation(t *testing.T) {
	pub := &mockPublisher{}
	r := NewRelay(nil, pub, WithInterval(time.Hour))

	ctx, cancel := context.WithCancel(context.Background())
	cancel()

	err := r.Start(ctx)
	require.Error(t, err)
	assert.ErrorIs(t, err, context.Canceled)
}

func TestNewInbox(t *testing.T) {
	inbox := NewInbox(nil)
	assert.NotNil(t, inbox)
}
